// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
    schema: "prisma/schema.prisma", // Prisma 模式文件路径
    migrations: {
        path: "prisma/migrations", // 迁移文件路径
    },
    datasource: {
        url: process.env["DATABASE_URL"], // 数据库连接 URL
    },
});
